kippo:
  image: dariusbakunas/kippo
  ports:
   - "2222:22"
  links:
   - db:mysql
graph:
  image: dariusbakunas/kippo-graph
  ports:
   - "80:80"
  links:
   - db:mysql
db:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: P@ssw0rd
